// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Debug provides a mock function with given fields: info
func (_m *Logger) Debug(info string) {
	_m.Called(info)
}

// Error provides a mock function with given fields: err
func (_m *Logger) Error(err string) {
	_m.Called(err)
}

// ErrorOp provides a mock function with given fields: err, op
func (_m *Logger) ErrorOp(err string, op string) {
	_m.Called(err, op)
}

// Fatal provides a mock function with given fields: err
func (_m *Logger) Fatal(err string) {
	_m.Called(err)
}

// Info provides a mock function with given fields: info
func (_m *Logger) Info(info string) {
	_m.Called(info)
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
